MODEL:
  NAME: SwinUNet
  TYPE: SWIN
  DROP_PATH_RATE: 0.2
  PRETRAINED: ""
  SWIN:
    VARIANT: tiny
    FINAL_UPSAMPLE: True
    PATCH_SIZE: 4
    EMBED_DIM: 96
    DEPTHS: [2, 2, 2, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7

DATASET:
  NAME: SYNAPSE
  N_CLASSES: 14
  N_CHANNELS: 1
  IMAGE_SIZE: [224, 224]
